# yaml-language-server: $schema=schema.json
# This is my local test file shared across multiple systems as i test so don't use this file as a reference

jobs:
  - name: echo
    concurrency: 3
    tasks:
      - command: echo {{ .Vars.name }}; sleep 5sec
        vars:
          name: '{{ now | date "2006-01-02_15-04-05" }}'
        env:
          COLE: test
        on-done:
          - command: echo {{ .Vars.name }}; sleep 1sec
        # connections:
        #   - image: "library/alpine"

    events:
      # - cron: "0 * * * * *"
      # - interval: 5s
      - on-init: true
      - web-event: test
      # - docker:
      #     image: nginx
