# yaml-language-server: $schema=schema.json

jobs:
  - name: echo
    tasks:
      - command: echo {{ now | date "2006-01-02_15-04-05" }}
        env:
          COLE: test
        on-done:
          - command: echo test $env.COLE
        # connections:
        #   - image: "library/alpine"

    events:
      # - cron: "0 * * * * *"
      # - interval: 5s
      - on-init: true
      - web-event: test
      # - docker:
      #     image: nginx
