# yaml-language-server: $schema=schema.json
# This is my local test file shared across multiple systems as i test so don't use this file as a reference

jobs:
  - name: echo
    concurrency: 3
    tasks:
      - command: echo $env.t{{ .Vars.name }}
        retry-delay: 1s
        retries: 0
        retry-jitter: 1s
        retry-mode: fibonacci
        vars:
          name: '{{ now | date "2006-01-02_15-04-05" }}'
        # connections:
        #   - image: "library/alpine"

    events:
      # - cron: "0 * * * * *"
      # - interval: 5s
      - on-init: true
      - web-event: test
      # - docker:
      #     image: nginx
